/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '5/3/20, 11:03 AM' 
 * Generated by 'u47496690' 
 * Generated on server 'ODAWS01-EUW1.ODA.SAS.COM' 
 * Generated on SAS platform 'Linux LIN X64 3.10.0-1062.9.1.el7.x86_64' 
 * Generated on SAS version '9.04.01M6P11072018' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36' 
 * Generated on web client 'https://odamid-euw1.oda.sas.com/SASStudio/main?locale=en_US&zone=GMT%252B03%253A00&https%3A%2F%2Fodamid-euw1.oda.sas.com%2FSASStudio%2F=' 
 *
 */

/* Define Pie template */
/* Crearea unui Pie Chart in functie de numarul biletelor vandute pe fiecare continent */
proc template;
	define statgraph SASStudio.Pie;
		begingraph;
		layout region;
		piechart category=Continent response=BileteVandute /;
		endlayout;
		endgraph;
	end;
run;

ods graphics / reset width=6.4in height=4.8in imagemap;
TITLE'Graficul biletelor vandute pe fiecare continent';
proc sgrender template=SASStudio.Pie data=LIBPRO.RAITING;
run;

ods graphics / reset;